version: "3.9"
services:
  app:
    container_name: golang_container
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    tty: true
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    command: air ./main.go
    #networks:
    #  - local

  postgresdb:
    image: postgres:alpine
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    #networks:
    #  - local

volumes:
  pg_data:
#networks:
#  local:
#    driver: bridge
